apps/coord/views.py
import MySQLdb
from flask import Blueprint
from flask import current_app as app
from flask import render_template, request
from flask.wrappers import Response
from slugify import slugify
from werkzeug.datastructures import Headers

from .constants import ExtEnum
from .track_file import makegpx, makejson, makekml

coord_bp = Blueprint("coord", __name__)

FORMATS = (
    {"ext": ExtEnum.GPX.value, "label": "GPX", "active": True},
    {"ext": ExtEnum.KML.value, "label": "KML"},
    {"ext": ExtEnum.GEOJSON.value, "label": "GeoJSON"},
    {"ext": ExtEnum.MAP.value, "label": "На карте"},
)


def get_project(project):
    lang, pr = project.split("wiki")
    if not pr:
        pr = "pedia"
    return "{}.wiki{}.org".format(lang, pr)


@coord_bp.route("/")
def index_coord():

    form = {}

    formats = {
        ExtEnum.KML.value: {
            "func": makekml,
            "ext": "kml",
            "ct": "application/vnd.google-earth.kml+xml",
        },
        ExtEnum.GPX.value: {
            "func": makegpx,
            "ext": "gpx",
            "ct": "application/gpx+xml",
        },
        ExtEnum.GEOJSON.value: {
            "func": makejson,
            "ext": "geojson",
            "ct": "application/vnd.geo+json",
        },
    }

    wiki = request.values.get("wiki", "ruwiki")
    category = request.values.get("category", "")
    not_primary = request.values.get("not_primary")
    ext = request.values.get("ext", "map")

    form["wiki"] = wiki
    form["category"] = category
    form["not_primary"] = not_primary
    form["ext"] = ext

    if not (category and ext in ("map", "kml", "gpx", "geojson")):
        return render_template("coord.html", form=form, formats=FORMATS, regions={})

    connection: MySQLdb.Connection = MySQLdb.Connect(
        host=app.config["DB_HOST"],
        port=app.config["DB_PORT"],
        user=app.config["DB_USER"],
        password=app.config["DB_PASS"],
        database="{}_p".format(wiki),
    )

    with connection:
        cursor: MySQLdb.cursors.Cursor
        with connection.cursor() as cursor:
            sql = """SELECT `page`.`page_title`,
                            `geo_tags`.`gt_name`,
                            `geo_tags`.`gt_primary`,
                            `geo_tags`.`gt_lat`,
                            `geo_tags`.`gt_lon`
                    FROM `geo_tags`
                    JOIN `page` ON `geo_tags`.`gt_page_id` = `page`.`page_id`
                    WHERE `gt_page_id` IN
                        (SELECT `cl_from`
                         FROM `categorylinks`
                         WHERE `cl_to` = %s)
                      AND `page_namespace` = 0
                      {};
                      """.format(
                "" if not_primary else "AND `gt_primary` = 1"
            )
            cursor.execute(sql, (category.replace(" ", "_"),))
            points = cursor.fetchall()

    if ext == ExtEnum.MAP.value or not points:
        return render_template(
            "coord.html",
            form=form,
            formats=FORMATS,
            points=makejson(points, category),
            project=get_project(wiki),
        )

    elif ext in formats.keys():
        filename = slugify(category)
        headers = Headers()
        headers.add(
            "Content-Disposition",
            "attachment",
            filename="{}.{}".format(filename, formats[ext]["ext"]),
        )
        response = Response(
            formats[ext]["func"](points, category, project=get_project(wiki)),
            headers=headers,
            content_type=formats[ext]["ct"],
        )
    else:
        response = render_template("coord.html", form=form, formats=FORMATS)

    return response

apps/gkgn/views.py
from typing import Any

from flask import Blueprint, render_template, request
from sqlalchemy import select

from apps.db import session

from .constants import LevelEnum
from .models import Object, Type

gkgn_bp = Blueprint("gkgn", __name__)


def to_int(value: Any) -> int:
    try:
        return int(value)
    except (TypeError, ValueError):
        return 0


@gkgn_bp.route("/")
def index_gkgn():

    result = []
    form = {}
    order_by = "name"

    if request.values.get("order_by") in ("gkgn_id", "name"):
        order_by = request.values["order_by"]

    form["gkgn_id"] = request.values.get("gkgn_id", "").lstrip("0")
    form["name"] = request.values.get("name", "")
    form["region_id"] = to_int(request.values.get("region_id"))
    form["district_id"] = to_int(request.values.get("district_id"))
    form["type_id"] = to_int(request.values.get("type_id"))

    query = (
        select(Object.id, Object.name)
        .where(Object.level == LevelEnum.REGION.value)
        .order_by(Object.name)
    )
    regions = session.execute(query).all()

    if form["region_id"]:
        query = (
            select(Object.id, Object.name)
            .where(
                Object.level == LevelEnum.DISTRICT.value,
                Object.region_id == form["region_id"],
            )
            .order_by(Object.name)
        )
        districts = session.execute(query).all()
    else:
        districts = []

    query = select(Type.id, Type.name).order_by(Type.name)
    types = session.execute(query).all()

    params = [getattr(Object, key) == value for key, value in form.items() if value]
    if params:
        query = select(Object).where(*params).order_by(getattr(Object, order_by))
        result = session.scalars(query).all()

    return render_template(
        "gkgn/index.html",
        regions=regions,
        districts=districts,
        types=types,
        result=result,
        len=len(result),
        form=form,
    )

apps/templates/base.html
<!DOCTYPE html>
<html lang="ru">

<head>
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <!-- Bootstrap CSS -->
  <link href="https://tools-static.wmflabs.org/cdnjs/ajax/libs/twitter-bootstrap/5.1.3/css/bootstrap.min.css"
    rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3"
    crossorigin="anonymous">

  {% if title %}
  <title>{{title}} - DimaBot</title>
  {% else %}
  <title>DimaBot</title>
  {% endif %}

  {% block extend_css %}{% endblock %}

</head>

<body>
  <div class="container-fluid ">
    <div class="row justify-content-center p-2">
      <div class="col col-10">
        <ul class="nav nav-tabs">
          <li class="nav-item"><a class="nav-link {% if nav_index %}active{% endif %}"
              href="{{ url_for('index') }}">Главная</a></li>
          <li class="nav-item"><a class="nav-link {% if nav_gkgn %}active{% endif %}"
              href="{{ url_for('gkgn.index_gkgn') }}">ГКГН</a></li>
          <li class="nav-item"><a class="nav-link {% if nav_coord %}active{% endif %}"
              href="{{ url_for('coord.index_coord') }}">Экспорт координат</a></li>
          <li class="nav-item"><a class="nav-link {% if nav_template_params %}active{% endif %}"
              href="{{ url_for('template_params.index') }}">Параметры шаблонов</a></li>
        </ul>
      </div>
      <div class="tab-content col col-10 mt-3">
        {% block content %}{% endblock %}
      </div>
    </div>
  </div>
  {% block extend_js %}{% endblock %}
</body>

</html>

apps/templates/coord.html
{% extends "base.html" %}

{% set nav_coord = True %}

{% block content %}
<form action="{{ url_for('coord.index_coord') }}" method="GET">
	<div class="row mb-3">
		<label for="wiki" class="col-sm-2 form-label">Проект:</label>
		<div class="col-sm-6">
			<input id="wiki" name="wiki" class="form-control" required value="{{ form.wiki }}">
		</div>
	</div>
	<div class="row mb-3">
		<label for="category" class="col-sm-2 form-label">Категория:</label>
		<div class="col-sm-6">
			<input id="category" name="category" class="form-control" required value="{{ form.category }}">
		</div>
	</div>
	<div class="row mb-3">
		<label class="col-sm-2 form-label">Опции:</label>
		<div class="col-sm-6">
			<div class="form-check form-check-inline">
				<input class="form-check-input" type="checkbox" name="not_primary" id="not_primary" {% if
					form.not_primary %}checked{% endif %}><label class="form-check-label"
					for="not_primary">Дополнительные координаты</label>
			</div>
		</div>
	</div>
	<div class="row mb-3">
		<label class="col-sm-2 form-label">Формат:</label>
		<div class="col-sm-6">
			{% for format in formats %}
			<div class="form-check form-check-inline">
				<input class="form-check-input" type="radio" name="ext" id="ext{{ loop.index }}" value="{{ format.ext }}" {% if form.ext==format.ext
					%}checked{% endif %}>
				<label class="form-check-label" for="ext{{ loop.index }}">{{ format.label }}</label>
			</div>{% endfor %}
		</div>
	</div>
	<div class="row mb-3">
		<div class="col-sm-2"></div>
		<div class="col-sm-6">
			<button type="submit" class="btn btn-outline-dark">Отправить</button>
		</div>
	</div>
</form>

{% if points %}
<div id="map" style="height: calc(100vh - 25rem); min-height: 500px;"></div>
{% endif %}
{% endblock %}

{% block extend_css %}
{% if points %}
<link rel="stylesheet" href="https://tools-static.wmflabs.org/cdnjs/ajax/libs/leaflet/1.7.1/leaflet.min.css" />
<link rel="stylesheet" href="https://tools-static.wmflabs.org/cdnjs/ajax/libs/leaflet.markercluster/1.5.0/MarkerCluster.min.css" />
<link rel="stylesheet" href="https://tools-static.wmflabs.org/cdnjs/ajax/libs/leaflet.markercluster/1.5.0/MarkerCluster.Default.min.css" />
<link rel="stylesheet" href="https://tools-static.wmflabs.org/cdnjs/ajax/libs/leaflet.fullscreen/2.0.0/Control.FullScreen.min.css" />
{% endif %}
{% endblock %}

{% block extend_js %}
{% if points %}
<script src="https://tools-static.wmflabs.org/cdnjs/ajax/libs/leaflet/1.7.1/leaflet.min.js"></script>
<script src="https://tools-static.wmflabs.org/cdnjs/ajax/libs/leaflet.markercluster/1.5.0/leaflet.markercluster.min.js"></script>
<script src="https://tools-static.wmflabs.org/cdnjs/ajax/libs/leaflet.fullscreen/2.0.0/Control.FullScreen.min.js"></script>

<script type="text/javascript">

	function desc_popup(feature) {
		return '<div class="text-center"><h5><b>' + feature.properties.name + '</b></h5></div> \
                      <div class="text-center"><b><a href="https://{{ project }}/wiki/' + feature.properties.title + '">Статья на Вики</a></b></div>'
	}

	var markerArray = [];

	var place_arr = {{ points| safe }};
	var project = '{{ project }}';

	var markers = L.markerClusterGroup({
		showCoverageOnHover: false,
		maxClusterRadius: 20
	});

	var osm_layer = L.tileLayer('https://maps.wikimedia.org/osm-intl/{z}/{x}/{y}.png', {
		attribution: 'Data: &copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors \
        	    			  Tiles: &copy; <a href="https://wikimediafoundation.org/w/index.php?title=Maps_Terms_of_Use#Where_does_the_map_data_come_from.3F">Wikimedia</a> contributors'
	});

	var map = L.map('map', {
		fullscreenControl: true,
		fullscreenControlOptions: {
			position: 'topleft'
		},
		layers: [osm_layer]
	});

	L.geoJSON(place_arr, {
		pointToLayer: function (feature, latlng) {
			var marker = L.marker(latlng).bindPopup(desc_popup(feature))
			markerArray.push(marker);
			return markers.addLayer(marker);
		}
	}).addTo(map);

	var group = L.featureGroup(markerArray);
	map.fitBounds(group.getBounds());

</script>
{% endif %}
{% endblock %}

apps/templates/index.html
{% extends "base.html" %}

{% set nav_index = True %}

{% block content %}
<h2>Привет!</h2>
<p>На этом сервере крутятся два бота - <a href="//ru.wikipedia.org/wiki/U:DimaBot">DimaBot</a> и <a
        href="//ru.wikipedia.org/wiki/U:DimaABot">DimaABot</a>. Домашней для них является википедия на русском языке, там же обитает их <a href="//ru.wikipedia.org/wiki/U:Dima st bk">хозяин</a>.
</p>
<p>Список задач обоих ботов можно найти на их страницах в РуВики.</p>
{% endblock %}